"""empty message

Revision ID: 611c767b0691
Revises: 
Create Date: 2021-11-22 22:58:43.333909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611c767b0691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('index', sa.INTEGER(), nullable=False),
    sa.Column('occupant', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('piece', sa.INTEGER(), nullable=False),
    sa.Column('hit', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('piece')
    op.drop_table('grid')
    # ### end Alembic commands ###
